name: Python CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9.19, "3.10.14", "3.11.9", "3.12.3"]
        include:
          - python-version: "nightly"
            continue-on-error: true

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
        continue-on-error: ${{ matrix.continue-on-error }}
      - name: Install dependencies
        run: pip install -q -r dev-requirements.txt --no-cache-dir --upgrade
      - name: Check format
        run: make check_format
      - name: Run tests
        run: make test
